#test
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-time-api
  labels:
    app: current-time-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: current-time-api
  template:
    metadata:
      labels:
        app: current-time-api
    spec:
      containers:
      - name: current-time-api
        image: kwood475/current-time-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: current-time-api-service 
  labels:
    app: current-time-api
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: current-time-api
